ENTRY(main)   /* the entrypoint is meaningless, since the boot sector is jumping to the code in kernel_entry.asm, which is the 'true' entrypoint */
SECTIONS
{
  .text 0x1000 :
  {
    code = .; _code = .; __code = .;
    *(.text)
    . = ALIGN(4096);
  }

  .data :
  {
     data = .; _data = .; __data = .;
     *(.data)
     *(.rodata)
     . = ALIGN(4096);
  }

  .bss :
  {
    bss = .; _bss = .; __bss = .;
    *(.bss)
    . = ALIGN(4096);
  }

  end = .; _end = .; __end = .;
}
